blueprint:
  name: Gradual Volume Reducer
  description: Reduces the volume of a media player gradually over time and resets after a certain number of iterations when media starts playing.
  domain: automation
  input:
    media_player:
      name: Media Player
      selector:
        entity:
          domain: media_player
    starting_volume:
      name: Starting Volume (Percentage)
      description: Initial volume of the media player (0-100).
      default: 50
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
    reduction_timeframe:
      name: Reduction Timeframe (Minutes)
      description: Timeframe over which the volume is reduced to 0.
      default: 100
      selector:
        number:
          min: 1
          max: 1440
          mode: slider
          step: 1
    reduction_iterations:
      name: Reduction Iterations
      description: Number of times the volume should reduce to 0 before stopping.
      default: 10
      selector:
        number:
          min: 1
          max: 100
          mode: slider
          step: 1

variables:
  media_player: !input 'media_player'
  starting_volume: !input 'starting_volume'
  reduction_timeframe: !input 'reduction_timeframe'
  reduction_iterations: !input 'reduction_iterations'
  volume_step: '{{ (starting_volume / 100) / (reduction_timeframe / 10) }}'
  total_iterations: '{{ reduction_timeframe / 10 * reduction_iterations }}'
  initial_volume_level: '{{ starting_volume / 100 }}'

trigger:
  - platform: state
    entity_id: !input 'media_player'
    to: 'playing'

action:
  - service: media_player.volume_set
    target:
      entity_id: !input 'media_player'
    data:
      volume_level: '{{ initial_volume_level }}'
  - delay:
      seconds: 1  # Small delay to ensure the volume is set before starting the loop
  - repeat:
      count: '{{ total_iterations }}'
      sequence:
        - service: media_player.volume_set
          target:
            entity_id: !input 'media_player'
          data:
            volume_level: >
              {{
                [
                  0,
                  (state_attr(media_player, 'volume_level') | float) - volume_step
                ] | max
              }}
        - delay:
            minutes: 10
  - service: media_player.media_stop
    target:
      entity_id: !input 'media_player'
  - service: media_player.volume_set
    target:
      entity_id: !input 'media_player'
    data:
      volume_level: '{{ initial_volume_level }}'
